tasks:
  - name: "Setup and UI Preview"
    init: npm install
    command: npm run start
ports:
  - port: 3000
    onOpen: open-browser

  - name: "Run ngrok"
    command: ngrok http 3000
    ports:
      - port: 4040
        onOpen: notify
